name: Genetrust Backend CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [22.x]
        python-version: [3.12.3]  # Changed to match your system Python version

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Start Python DNA Prediction Server
      working-directory: ./genepredictor
      run: |
        # Kill any existing Python processes
        pkill -f "python app.py" || true
        
        # Make script executable
        chmod +x run_server.sh
        
        # Start the server in the background using the non-venv script
        bash run_server.sh &
        
        # Wait for the server to be ready
        for i in {1..30}; do
          if curl -s http://localhost:4000/health > /dev/null; then
            echo "Python server is up!"
            break
          fi
          if [ $i -eq 30 ]; then
            echo "Timeout waiting for Python server"
            exit 1
          fi
          echo "Waiting for Python server to start... (Attempt $i/30)"
          sleep 2
        done

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./backend/package-lock.json

    - name: Create .env file from PROD_ENV_FILE secret
      working-directory: ./backend
      run: echo "${{ secrets.PROD_ENV_FILE }}" > .env

    - name: Install dependencies
      working-directory: ./backend
      run: |
        if [ -d "node_modules" ]; then
          echo "node_modules already exists. Skipping install."
        else
          echo "Installing dependencies..."
          npm ci
        fi

    - name: Build TypeScript
      working-directory: ./backend
      run: npm run build

    - name: Manage PM2 node processes
      working-directory: ./backend
      run:        
          pm2 restart genetrust-node
        else
          pm2 start npm --name genetrust-backend -- run start
          
    - name: Manage PM2 python processes
      working-directory: ./genepredictor
      run:        
          pm2 restart genetrust-python
        else
          pm2 start npm --name genetrust-python -- run start

